apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
  labels:
    app: compliment-generator
    version: "latest"
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  selector:
    app: compliment-generator
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
  labels:
    app: compliment-generator
    version: "latest"
spec:
  replicas: 4
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
        version: "latest"
    spec:
      containers:
      - name: compliment-generator
        image: "latest"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 2
          httpGet:
            path: /
            port: 5000